2019-02-28 22:28:02,271:__main__:Tried to divide by zero
Traceback (most recent call last):
  File "C:\Users\532975\Documents\Automation\Learn\Python\Logging\custom_logger\custom_logger_v2.py", line 40, in divide
    result = x / y
ZeroDivisionError: division by zero
